🍋POST機能の追加
aoi0124/pbl pull request #5
Opened 2023-10-16 12:58 UTC by aoi0124

2023-10-16 15:07 UTC, taikis requested changes
ファイルのスペルミス直して

2023-10-16 15:07 UTC, taikis commented on templates/rogin.html
loginのスペルミス

2023-10-16 16:12 UTC, aoi0124 reviewed
修正しました。

2023-10-17 00:22 UTC, taikis approved these changes
🙆

2023-10-17 00:48 UTC, merged